apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: naive-cryptocurrency-pow-rpc-peer-app
spec:
  serviceName: naive-cryptocurrency-pow-rpc-peer-app-service
  replicas: 1
  selector:
    matchLabels:
      app: naive-cryptocurrency-pow-rpc-peer-app
  template:
    metadata:
      labels:
        app: naive-cryptocurrency-pow-rpc-peer-app
    spec:
      containers:
      - name: naive-cryptocurrency-pow-rpc-peer-app
        image: brandonjroberts/naive-rpc-node:latest
        imagePullPolicy: Always
        env:
          - name: PEER_TO_CALL
            value: "/ip4/10.244.0.28/tcp/8985/p2p/QmdMb8vvdTJ1gR29jZKoWqbPdB4heFuGwjFckSyTzd9f13"
        ports:
        - containerPort: 8985
        - containerPort: 8986
        - containerPort: 8987
          #        volumeMounts:
          #        - name: pow-snapshot
          #          mountPath: /app/snapshot
          #  volumeClaimTemplates:
          #  - metadata:
          #      name: pow-snapshot
          #    spec:
          #      accessModes: [ "ReadWriteOnce" ]
          #      resources:
          #        requests:
          #          storage: 1Gi
          #          TODO
---
apiVersion: v1
kind: Service
metadata:
  name: naive-cryptocurrency-pow-rpc-peer-app-service
spec:
  selector:
    app: naive-cryptocurrency-pow-rpc-peer-app
  ports:
  - name: http
    protocol: TCP
    port: 8987
    targetPort: 8987

