{
 "title": "Local Geth Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Chains",
    "query": "geth-l1-miner,geth-l1-rpc,geth-l2-sequencer,geth-l2-rpc"
   }
  ]
 },
 "panels": [
  { "title": "L1-L2 Smart Contract Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Batches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "batch_count{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Batches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "last_confirmed_batch{job=\"l2-smart-contract-exporter\"} + 1 * (batch_count > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed Batches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "batch_count{job=\"l2-smart-contract-exporter\"} - last_confirmed_batch{job=\"l2-smart-contract-exporter\"} - 1 * (batch_count > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_count{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Blockheight when collected",
   "type": "stat",
   "description": "L1 blockheight when latest round of metrics created",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l1_block_height{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Batch's L1 Block",
   "type": "stat",
   "description": "L1 Block containing the latest batch's smart contract transaction calling \"StoreBatch\"",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_batch_l1_block{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Batch's Proof L1 Block",
   "type": "stat",
   "description": "L1 Block containing the latest batch's zk proof smart contract transaction, calling \"ProveBatch\" (0 if none)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_batch_proof_l1_block{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Batches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_confirmed_batch{job=\"l2-smart-contract-exporter\"} + 1 * (batch_count > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Confirmed Batch's L1 Block",
   "type": "stat",
   "description": "L1 Block containing the latest confirmed batch's smart contract transaction calling \"StoreBatch\"",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_confirmed_batch_l1_block{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Confirmed Proof's L1 Block",
   "type": "stat",
   "description": "L1 Block containing the latest confirmed batch's zk proof smart contract transaction, calling \"ProveBatch\"",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_confirmed_batch_proof_l1_block{job=\"l2-smart-contract-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prover", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Proofs Submitted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "prover_total_proofs{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Proofs Verified",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "prover_total_proofs_verified{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rewards",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "prover_total_rewards{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Proofs Submitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_total_proofs{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_total_rewards{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Proofs Verified",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_total_proofs_verified{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l1_block_height{job=\"l2-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain Metrics : $Chains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "Chains" },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Chain Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "chain_head_block{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Chain Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 41 },
   "targets": [
    {
     "expr": "txpool_invalid{job=\"$Chains\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "txpool_pending{job=\"$Chains\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "txpool_queued{job=\"$Chains\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "txpool_local{job=\"$Chains\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "txpool_known{job=\"$Chains\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "txpool_valid{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Pool Invalid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_invalid{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Pool Valid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_valid{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Pool Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Pool Queued",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Dials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "p2p_dials{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 57 },
   "targets": [
    {
     "expr": "rpc_requests{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status RPCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 57 },
   "targets": [
    {
     "expr": "rpc_failure{job=\"$Chains\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rpc_success{job=\"$Chains\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "System Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_memory_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_disk_readdata", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "system_cpu_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Write Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_disk_writedata", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Docker Containers Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}