apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: naive-blockchain-pow-app
spec:
  serviceName: naive-blockchain-pow-app-service
  replicas: 1
  selector:
    matchLabels:
      app: naive-blockchain-pow-app
  template:
    metadata:
      labels:
        app: naive-blockchain-pow-app
    spec:
      containers:
      - name: naive-blockchain-pow-app
        image: brandonjroberts/naive-cryptocurrency-pow:0.0.1-I1
        #command: ["./main", "--port=10000", "--snap=/app/snapshot/snapshot.tmp"]
        command: ["./main", "--port=10000"]
        ports:
        - containerPort: 10000
        volumeMounts:
        - name: pow-snapshot
          mountPath: /app/snapshot
  volumeClaimTemplates:
  - metadata:
      name: pow-snapshot
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

