name: GitHub Actions
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on: [push]
jobs:
  Build-Eth-Private-Network:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: eth-private-network/go-ethereum/go.sum

      - name: Build Eth Private Network
        working-directory: ./eth-private-network/
        run: make build

      - name: List files
        working-directory: ./eth-private-network/
        run: ls eth-private-network/go-ethereum/

      - name: Run Miner Node
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          working-directory: ./eth-private-network
          command_line: timeout 30s make run-miner
          contains: number=10
          expected_result: PASSED
