name: GitHub Actions
run-name: ${{ github.actor }} is running GitHub Actions to test & deploy MyBlockchains 🚀
on: [push]
jobs:
  Run-Eth-Private-Network-Miner:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: eth-private-network/go-ethereum/go.sum

      - name: Build Eth Private Network
        working-directory: ./eth-private-network/
        run: make build

      - name: List files
        working-directory: ./eth-private-network/
        run: ls go-ethereum/

      - name: Run Miner Node
        working-directory: ./eth-private-network/
        run: OUTPUT_FILE=out-miner.txt make run-miner-daemon && sleep 30s

      - name: Show Miner Logs
        working-directory: ./eth-private-network/
        run: cat out-miner.txt

      - name: Confirm Miner Mined 10 Blocks
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat eth-private-network/out-miner.txt
          contains: number=10
          expected_result: PASSED

      - name: Run RPC Node
        working-directory: ./eth-private-network/
        run: OUTPUT_FILE=out-rpc.txt make run-rpc-daemon && sleep 15s

      - name: Connect Miner & RPC as peers
        working-directory: ./eth-private-network/
        run: make connect-peers && sleep 15s

      - name: Show RPC Logs
        working-directory: ./eth-private-network/
        run: cat out-rpc.txt
