name: GitHub Actions
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on: [push]
jobs:
  Build-Eth-Private-Network:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Go into Eth Private Network Dir
        run: cd eth-private-network/

      - name: Ls
        run: ls

      - name: Pwd
        run: pwd

      - name: Build Eth Private Network
        run: make build
