name: GitHub Actions
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on: [push]
jobs:
  Build-Eth-Private-Network:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Eth Private Network
        run: cd eth-private-network && make build

      - name: List files
        run: ls eth-private-network

      - name: Run Miner Node
        run: cd eth-private-network && make run-miner
