name: Naive L2 Cryptocurrency Docker
run-name: ${{ github.actor }} is Building & Pushing Docker Images for MyBlockchains/naive-blockchain/naive-cryptocurrency-l2 🚀
on:
  push:
    paths:
      - "naive-blockchain/naive-cryptocurrency-l2/**"
      - ".github/workflows/l2-cryptocurrency-docker.yml"
jobs:
  Docker-Build-Sequencer:
    # TODO: Reduce code duplication here
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/naive-l2-sequencer

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Info
        run: echo "Parameters. ${{ github.ref }}, ${{ github.sha }}"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=raw,value=latest,priority=1000,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=semver,pattern={{raw}},priority=900
            type=raw,value={{branch}}-{{sha}},priority=800,enable=${{ github.ref != format('refs/heads/{0}', 'master') && startsWith(github.ref, 'refs/heads/') }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Sequencer Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./naive-blockchain/naive-cryptocurrency-l2/
          push: 'true'
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          file: ./naive-blockchain/naive-cryptocurrency-l2/docker/Dockerfile.sequencer

  Docker-Build-Prover:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/naive-l2-prover

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Info
        run: echo "Parameters. ${{ github.ref }}, ${{ github.sha }}"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=raw,value=latest,priority=1000,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=semver,pattern={{raw}},priority=900
            type=raw,value={{branch}}-{{sha}},priority=800,enable=${{ github.ref != format('refs/heads/{0}', 'master') && startsWith(github.ref, 'refs/heads/') }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Prover Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./naive-blockchain/naive-cryptocurrency-l2/
          push: 'true'
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          file: ./naive-blockchain/naive-cryptocurrency-l2/docker/Dockerfile.prover

  Docker-Build-Smart-Contract-Exporter:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/naive-l2-smart-contract-exporter

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Info
        run: echo "Parameters. ${{ github.ref }}, ${{ github.sha }}"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=raw,value=latest,priority=1000,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=semver,pattern={{raw}},priority=900
            type=raw,value={{branch}}-{{sha}},priority=800,enable=${{ github.ref != format('refs/heads/{0}', 'master') && startsWith(github.ref, 'refs/heads/') }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Smart Contract Exporter Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./naive-blockchain/naive-cryptocurrency-l2/
          push: 'true'
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          file: ./eth-private-network/docker/Dockerfile.smart-contract-exporter
