name: Naive L2 Cryptocurrency Actions
run-name: ${{ github.actor }} is Running Actions to Deploy & Test MyBlockchains/naive-blockchain/naive-cryptocurrency-l2 🚀
on:
  push:
    paths:
      - "naive-blockchain/naive-cryptocurrency-l2/**"
      - ".github/workflows/l2-cryptocurrency-actions.yml"
jobs:
  Run-Eth-Private-Network:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: naive-blockchain/naive-cryptocurrency-l2/go.sum

      - name: Install solcjs
        run: npm install -g solc@0.8.18

      - name: solcjs version
        run: solcjs --version

      - name: PWD
        run: pwd

      - name: NPM Install Dependencies
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/contracts/
        run: npm install

      - name: Build Geth Devtools
        working-directory: ./eth-private-network/go-ethereum
        run: make devtools

      - name: abigen version
        run: abigen --version

      - name: Build All Contracts & L2
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/
        run: make all

      - name: List files
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/
        run: ls build/

      - name: Build Eth Private Network to run as L1
        working-directory: ./eth-private-network/
        run: make build

      - name: Build Geth for L2 Sequencer
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/go-ethereum
        run: make geth

      - name: Run L1 Miner Node
        working-directory: ./eth-private-network/
        run: OUTPUT_FILE=out-miner.txt make run-miner-daemon && sleep 30

      - name: Show L1 Miner Logs
        working-directory: ./eth-private-network/
        run: cat out-miner.txt

      - name: Confirm Miner is running ( Mined 10 blocks )
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat eth-private-network/out-miner.txt
          contains: number=10
          expected_result: PASSED 

      - name: Deploy Contracts onto L1
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/
        run: make deploy-l1-contracts

      - name: Run L2 Sequencer
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/
        run: OUTPUT_FILE=out-sequencer.txt make run-sequencer-github-actions-retry && sleep 120s

      - name: Confirm Sequencer Stored Genesis on L1
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat ./naive-blockchain/naive-cryptocurrency-l2/out-sequencer.txt
          contains: Stored genesis state on L1
          expected_result: PASSED

      - name: Confirm Sequencer is running ( Mined 10 blocks )
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat ./naive-blockchain/naive-cryptocurrency-l2/out-sequencer.txt
          contains: number=10
          expected_result: PASSED

      - name: Deploy Contracts onto L2
        working-directory: ./naive-blockchain/naive-cryptocurrency-l2/
        run: make deploy-l2-contracts-github-actions
